//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.ComponentModel.EditorAttribute("SemanticVersion", "777.0.0.0-212-snapshot-eap01d")]
[assembly: global::System.ComponentModel.EditorAttribute("Version4", "777.0.0.0")]
[assembly: global::System.ComponentModel.EditorAttribute("WaveMarketingName", "2021.2 EAP 1 D")]
[assembly: global::System.ComponentModel.EditorAttribute("WaveMarketingNameCompressed", "2021.2EAP1D")]
[assembly: global::System.Reflection.AssemblyCompanyAttribute("JetBrains")]
[assembly: global::System.Reflection.AssemblyCopyrightAttribute("Copyright © 2000-2021 JetBrains")]
[assembly: global::System.Reflection.AssemblyFileVersionAttribute("777.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("Plugins\\fsharp-support\\ReSharper.FSharp\\src")]
[assembly: global::System.Reflection.AssemblyVersionAttribute("777.0.0.0")]